### ISSUE TITLE
Why full text of an articles sometimes is not available ?

### ISSUE THREAD

**Issue by unoexperto** [ncbi/JATSPreviewStylesheets#12]
Hey guys, sorry for asking this question here but I figured somebody who is aware of NCBI infrastructure is reading this.

Could you please explain why full text of an articles sometimes is not available ?

Let's use this article as an example
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2907408/

EFetch gives only abstract
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&retmode=xml&rettype=full&id=2907408

and oai.cgi says it doesn't exist at all !
http://www.ncbi.nlm.nih.gov/pmc/oai/oai.cgi?verb=GetRecord&metadataPrefix=pmc&identifier=oai:pubmedcentral.nih.gov:2907408

How can I get this article ?

Thank you!

**Comment by Klortho** [comment]
The PMC [Open Access Subset](http://www.ncbi.nlm.nih.gov/pmc/tools/openftlist/) page gives a good description of these policies.

If you still have questions after checking that out, you can write to the PMC help desk: pubmedcentral@ncbi.nlm.nih.gov. They are very responsive.
